version: "3.1"

services:
  MySQL:
    #platform: linux/x86_64 #En caso de trabajar en arm64
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - "./Databases/mysql/.data/db:/data/db"
    container_name: MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    ports:
      - 3307:3306